config/routes.rb
IMSRails3::Application.routes.draw do
  
  resources :users do
    collection  do
      post 'verify_login'
      get 'search'
    end
  end

  resources :interviews do
    collection do
      get 'csv_upload'
      post 'import_csv'      
      get 'search'
    end    
  end
  match 'interview/:id/download_attachment/:attachment_id' => "interviews#download_attachment",:as=>"download_attachment"
  match 'interview/upload_personal_doc/:id' => "interviews#upload_personal_doc",:as=>"upload_personal_doc"

  match 'interview/import_personal_doc/:id' => "interviews#import_personal_doc",:as=>"import_personal_doc"
  match 'interview/index' => "interviews#get_content_to_display",:as=>"get_content_to_display"

  match 'logout' => "users#logout",:as=>"logout"
  root :to => "users#login"
  

end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
 #ankit did it
 #before_filter :authenticate
  # GET /interviews
  # GET /interviews.xml
  def index
    params[:page] ||=1
    @interviews_csv = Interview.all
    @interviews = Interview.paginate(:per_page=>8,:page=>params[:page])
     
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @interviews }
      format.csv { generate_csv_headers("Interview-#{Time.now.strftime("%Y%m%d")}") }
      format.json {render :json => @interviews_csv}
    end
  end

  # GET /interviews/1
  # GET /interviews/1.xml
  def show
    @interview = Interview.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @interview }
      format.pdf { render :layout => false }
      format.json { render :json => @interview }
    end
    
  end
 
  # GET /interviews/new
  # GET /interviews/new.xml
  def new
    @interview = Interview.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @interview }
    end
  end

  # GET /interviews/1/edit
  def edit
    @interview = Interview.find(params[:id])
  end

  # POST /interviews
  # POST /interviews.xml
  def create
    @interview = Interview.new(params[:interview])

    respond_to do |format|
      if @interview.save
        format.html { redirect_to(@interview, :notice => 'Interview was successfully created.') }
        format.xml  { render :xml => @interview, :status => :created, :location => @interview }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @interview.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /interviews/1
  # PUT /interviews/1.xml
  def update
    @interview = Interview.find(params[:id])

    respond_to do |format|
      if @interview.update_attributes(params[:interview])
        format.html { redirect_to(@interview, :notice => 'Interview was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @interview.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /interviews/1
  # DELETE /interviews/1.xml
  def destroy
    @interview = Interview.find(params[:id])
    @interview.destroy

    respond_to do |format|
      format.html { redirect_to(interviews_url) }
      format.xml  { head :ok }
    end
  end

  def csv_upload
    
  end
  
  def import_csv
    #   begin
    file = params[:csv_import][:file]
    logcount=0
    Interview.transaction do
      FasterCSV.parse(file.tempfile, :headers => true) do |row|
        Interview.create!(row.to_hash)
        logcount += 1
      end
    end
    flash[:notice] = "Successfully added #{logcount} Participant(s)."
    redirect_to interviews_path
  rescue => exception
    # If an exception is thrown, the transaction rolls back and we end up in this rescue block
    error = ERB::Util.h(exception.to_s) # get the error and HTML escape it
    flash[:error] = "Please Check The File Being uploaded.Check File Format and CSV Headers.Please try again.(#{error})"
    redirect_to csv_upload_interviews_url
     
  end

  def upload_personal_doc
    @interview = Interview.find params[:id]
    render :layout => "popup"
  end

  def import_personal_doc    
    @interview = Interview.find(params[:id])
    @attachment = @interview.attachments.new(params[:attachment])
    @attachment.save
  end
  
  def download_attachment
    @attachment = Attachment.find(params[:attachment_id])
    send_file @attachment.data.path
  end

  def search    
    @search = Interview.search(params[:search])
    @interviews = @search.all.paginate(:per_page=>8,:page=>params[:page])
    @interviews_csv = @search
    respond_to do |format|
      format.csv do
        generate_csv_headers("Interview-#{Time.now.strftime("%Y%m%d")}")
        render :action=>:index
      end
      format.html { render :action=>:index }
    end
  end 

  def generate_csv_headers(filename)
    headers.merge!({
        'Cache-Control'             => 'must-revalidate, post-check=0, pre-check=0',
        'Content-Type'              => 'csv',
        'Content-Disposition'       => "attachment; filename=\"#{filename}\"",
        'Content-Transfer-Encoding' => 'binary'
      })
  end
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/views/interviews/_form.html.erb
<div class="mainbox" id="mainbox" >
  <%= form_for(@interview) do |f| %>
    <% if @interview.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@interview.errors.count, "error") %> prohibited this interview from being saved:</h2>
        <ul>
          <% @interview.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <div id="dialog">
      <table id="form1">
        <tr>
        <div class="field">
          <th>CV Recieved <%= f.label :ON %><br /></th><td>
            <%= f.text_field :cv_recieved_on %></td>
        </div></tr><tr>
        <div class="field">
          <th>Recieved <%= f.label :From %><br /></th><td>
            <%= f.text_field :recieved_from %></td>
        </div></tr><tr>
        <div class="field">
          <th>Resource <%= f.label :Name %><br /></th><td>
            <%= f.text_field :resource_name %></td>
        </div></tr><tr>
        <div class="field">
          <th>For <%= f.label :Location %><br /></th><td>
            <%= f.select(:for_location, Interview::For_Location) %></td>
        </div></tr><tr>
        <div class="field">
          <th><%= f.label :Skills %><br /></th><td>
            <%= f.text_field :skills %></td>
        </div></tr><tr>
        <div class="field">
          <th>Total <%= f.label :Experience %><br /></th><td>
            <%= f.text_field :total_experience %></td>
        </div></tr><tr>
        <div class="field">
          <th>Contact <%= f.label :Number %><br /></th><td>
            <%= f.text_field :contact_number %></td>
        </div></tr><tr>
        <div class="field">
          <th><%= f.label :Source %><br /></th><td>
            <%= f.text_field :source %></td>
        </div></tr><tr>
        <div class="field">
          <th><%= f.label :Status %><br /></th><td>
            <%= f.select(:status, Interview::Status) %></td>
        </div></tr><tr>
        <div class="field">
          <th><%= f.label :Remarks %><br /></th><td>
            <%= f.text_area :remarks %></td>
        </div></tr><tr>
        <div class="field">
          <th>Date Of <%= f.label :Interview %><br /></th><td>
            <%= f.text_field :date_of_interview %></td>
        </div></tr><tr>
        <div class="field">
          <th>First <%= f.label :Round %><br /></th><td>
            <%= f.select(:first_round, Interview::First_Round) %></td>
        </div></tr><tr>
        <div class="field">
          <th>Second <%= f.label :Round %><br /></th><td>
            <%= f.select(:second_round, Interview::Second_Round) %></td><tr>
        <div class="field">
          <th>MR <%= f.label :Round %><br /></th><td>
            <%= f.select(:mr_round, Interview::MR_Round) %></td>
        </div></tr><tr>
        <div class="field">
          <th>E-<%= f.label :Mail %><br /></th><td>
            <%= f.text_field :email %></td>
        </div></tr><tr>
        <div class="field">
          <th>Date Of <%= f.label :Joining %><br /></th><td>
            <%= f.text_field :date_of_joining %></td>
        </div></tr>
      </table>
      <div class="actions">
        <center><tr><%= f.submit %></tr>
      </div></tr>
    <% end %>
  </div>
</div>

app/views/interviews/edit.html.erb
<%=render :partial=>"search"%>
<div class="column contactlist">
  <div class="mainbox">
    <div class="menu">
      <% content_for :head do %>
        <li><%=link_to "Export Search Results", request.parameters.merge({:format => :csv}),{:class=>"export"}%></li>
        <li><%=link_to "Add New Candidates", new_interview_path%></li>
      <% end %>
<h1>Editing interview</h1>
<center>

<%= render 'form' %>

</div>

app/views/interviews/index.csv.erb
<%- headers = ["Serial Number", "CV Recieved On","Resource Name","For Location","Skills","Total Experience","Contact#","Source","Status","Remarks","Date of Interview","First Round","Second Round","MR Round","E-Mail","Date Of Joining"] -%>
<%  tsv_str = FasterCSV.generate(:col_sep => "\t") do |tsv| %>
 <%  tsv << headers %>
<% end %>
<% i=1 %>
<%- @interviews_csv.each do |n| -%>
<%- row = [i,n.cv_recieved_on.strftime("%d/%m/%Y"),n.resource_name,n.for_location,n.skills,n.total_experience,n.contact_number,n.source,n.status,n.remarks,n.date_of_interview,n.first_round,n.second_round,n.mr_round,n.email,n.date_of_joining ] -%>
<% i= i+1 %>
  <%  tsv_str = FasterCSV.generate(:col_sep => "\t") do |tsv| %>
 <%  tsv << row %>
<% end %>
<% end %>

app/views/interviews/index.html.erb
<%=render :partial=>"search"%>
<div class="column contactlist">
  <div class="mainbox">
    <div class="menu">
      <% content_for :head do %>
        
        <li><%=link_to "Add New Candidates", new_interview_path%></li>
      <% end %>
    </div>
    <div class="displaying" >
      <%= page_entries_info @interviews %>
      <div style="margin-left:700px; position:absolute; margin-bottom: 10px;">Export<%= link_to image_tag("Excel.png", :alt => "Export as Excel", :title => "Export as Excel",:remote=>true,:width => 20, :height => 25), request.parameters.merge({:format => :csv})%></div>
    </div><br>
    <%if @interviews.blank?%>
      <h3>  No Results Found</h3>
    <%end%>
    <table id="ashish"class="standard_table" cellpadding="0" cellspacing="0" >
      <tbody><tr class="list">

          <th>Resource Name</th>
          <th>Status</th>
          <th>Recieved From</th>
          <th>CV Recieved ON</th>
          <th>Document List</th>
          <th>Document Import</th>
        </tr><% j=1 %>
        <% @interviews.each_with_index do |interview,i| %>
          <tr class="<%=cycle('', 'alt_row')%>">

            <td>
              <%= link_to "#{h interview.resource_name.upcase}",interview,:id=>"candidate_#{h interview.id}" ,:class => 'details' %></td>
            <td><%=h interview.status %></td>
            <td><%=h interview.recieved_from %></td>
            <td><%=h interview.cv_recieved_on.strftime("%d/%m/%Y")  %>

            <td><%interview.attachments.each_with_index do |attachment,i|%>
                <%= link_to "#{attachment.data_file_name}", download_attachment_url(:id=>interview.id,:attachment_id=>attachment.id) %>
                <%= "," if i+1 < interview.attachments.length%>
              <%end%>
            </td>
            <td><%=  link_to image_tag("paperclip_icon.png", :alt => "Upload File", :title => "UPLOAD",:width => 20, :height => 20), "javascript:void(0);",:onclick=>"window.open('#{upload_personal_doc_url(:id=>interview.id)}','Import Document','Height=75px;width=150px;')" %>
              <%=  link_to image_tag("Symbols Delete.png", :alt => "Delete", :title => "DELETE",:remote=>true,:width => 20, :height => 25), interview, :confirm => 'Are you sure?', :method => :delete %>
            </td> </td>
          </tr><% j=j+1 %>
        <% end %>
      </tbody>
    </table>
    <%=will_paginate @interviews%>
    <div class="clear"></div>
  </div></div>

app/views/interviews/new.html.erb
<%=render :partial=>"search"%>
<div class="column contactlist">
  <div id="new1" class="mainbox">
    <div class="menu">
      <% content_for :head do %>
        <li><%=link_to "Export Search Results", request.parameters.merge({:format => :csv}),{:class=>"export"}%></li>
        <li><%=link_to "Add New Candidates", new_interview_path%></li>
      <% end %>
<%= render 'form' %>
<%= link_to 'Back', interviews_path %>
</div>


    

app/views/interviews/show.html.erb
<%=render :partial=>"search"%>
<div class="column contactlist">
  <div class="mainbox">
    <div class="menu">
      <% content_for :head do %>
        <li><%=link_to "Export Search Results", request.parameters.merge({:format => :csv}),{:class=>"export"}%></li>
        <li><%=link_to "Add New Candidates", new_interview_path%></li>
      <% end %>

      <p id="notice"><%= notice %></td></tr>
      <div id ="test">
        <table id="form3">
          <caption><center><b>Details of <%= @interview.resource_name.upcase %> </b></center></caption>
          <th>Experience:</th><td>
            <%= @interview.cv_recieved_on.strftime("%d/%m/%Y") %>
          </td></tr>
          <tr>
            <th>Recieved From:</th><td>
              <%= @interview.recieved_from %>
            </td></tr>
          <tr>
            <th>For Location:</th><td>
              <%= @interview.for_location   %>
            </td></tr>
          <tr>
            <th>Skills:</th><td>
              <%= @interview.skills %>
            </td></tr>
          <tr>
            <th>Total Experience:</th><td>
              <%= @interview.total_experience %>
            </td></tr>
          <tr>
            <th>Contact Number:</th><td>
              <%= @interview.contact_number %>
            </td></tr>
          <tr>
            <th>Source:</th><td>
              <%= @interview.source %>
            </td></tr>
          <tr>
            <th>Status:</th><td>
              <%= @interview.status %>
            </td></tr>
          <tr>
            <th>Remarks:</th><td>
              <%= @interview.remarks %>
            </td></tr>
          <tr>
            <th>Date of Interview:</th><td>
               <% if @interview.date_of_interview.nil? %>
          <p>Not Applicable</p>
          <% else %>
              <%= @interview.date_of_interview.strftime("%d/%m/%Y") %>
          <% end %>
            </td></tr>
          <tr> 
            <th>Date of Joining:</th><td>
              <% if @interview.date_of_joining.nil? %>
          <p>Not Applicable</p>
          <% else %>
              <%= @interview.date_of_joining.strftime("%d/%m/%Y") %>
          <% end %>
            </td></tr>
          <tr>
            <th>First Round:</th><td>
              <%= @interview.first_round %>
            </td></tr>
          <tr>
            <th>Second Round:</th><td>
              <%= @interview.second_round %>
            </td></tr>
          <tr>
            <th>MR Round:</th><td>
              <%= @interview.mr_round %>
            </td></tr>
          <tr>
            <th>E-Mail:</th><td>
              <%= @interview.email %>
            </td></tr>
          <tr>


            <td><center><%= link_to 'Edit', edit_interview_path(@interview),:class =>"button_height ui-state-default ui-corner-all" %></td>
            <td><center><%= link_to 'Back', interviews_path,:class =>"button_height ui-state-default ui-corner-all" %></td>


          </tr>
        </table>
      </div>



      <%=  link_to_function("Print this Page", "javascript:print()")%>
    </div>
  </div>