config/routes.rb
IMSRails3::Application.routes.draw do
  
  resources :users do
    collection  do
      post 'verify_login'
      get 'search'
    end
  end

  resources :interviews do
    collection do
      get 'csv_upload'
      post 'import_csv'      
      get 'search'
    end    
  end
  match 'interview/:id/download_attachment/:attachment_id' => "interviews#download_attachment",:as=>"download_attachment"
  match 'interview/upload_personal_doc/:id' => "interviews#upload_personal_doc",:as=>"upload_personal_doc"

  match 'interview/import_personal_doc/:id' => "interviews#import_personal_doc",:as=>"import_personal_doc"
  match 'interview/index' => "interviews#get_content_to_display",:as=>"get_content_to_display"

  match 'logout' => "users#logout",:as=>"logout"
  root :to => "users#login"
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html><head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-type">
      <title>IMS</title>
      <%= stylesheet_link_tag 'ims','form','jquery.lightbox-0.5' %>
      <%= stylesheet_link_tag 'ims_templates' %>
      <%= stylesheet_link_tag "jquery-ui", "application","jquery.ui.autocomplete" %>
      <%= javascript_include_tag "jquery.min", "jquery-ui.min", "application","jquery.lightbox-0.5" %>
      <%= stylesheet_link_tag 'Style' %>
      <%= stylesheet_link_tag 'main' %>
      <%= csrf_meta_tag %>
      <%= javascript_include_tag "rails" %>
  </head>

  <body bgcolor="#F0F0FF">

    <!-- Main -->
    <!--div id="main" class="box"-->
    <div id="main" >
      <div id="main" >

        <!-- Header -->
        <div id="header">
          <!-- Logotyp -->

          <h1 id="logo"> 	<span title="IMS (Go to homepage)" onclick="location.href='/interviews'" style="cursor:pointer" >   Interview Management System</span></h1>

        </div>

  <marquee><b> Please click on the link to see resources on mobile ! <b></marquee>
<h2><b><a href="/www/index.html">Mobile Version</a></b></h2>

      </div>



      <div id="user">
        <div id="tabs" class="noprint">

          <ul class="box" id="mainMenu">
            
            <li <%= 'id=active' unless params[:controller] != 'home'%>>
              <%= link_to 'View All Candidates', interviews_path%>
            </li>
            <li <%= 'id=active' unless params[:controller] != 'home'%>>

              <%= link_to 'Import Data via CSV File', csv_upload_interviews_url%>
            </li>
            
            <li <%= 'id=active' unless params[:controller] != 'home'%>>
              <%= link_to 'Users', users_url %>
            </li>
           
 <%= yield :head %>
          </ul>
          
        </div>
        <% if @user %>
        <label id="username">User Logged In : <%= @user.firstname%> <%= @user.lastname %></label>
        <%= link_to 'Logout', logout_url%>

        <% end %>
      </div>


      <!-- Page (2 columns) -->
      <!--div id="page" class="box"-->
      <div id="page">
        <!--div id="page-in" class="box"-->
        <div id="page-in" >

          <div id="strip" class="box noprint">
            <p id="sso"></p>
            <strong>
              <div>

              </div>
            </strong>
            <hr class="noscreen" />
          </div> <!-- /strip -->
          <%=yield%>
          <!-- Content -->
          <div id="content">
            <!-- Article --><center>
              <!-- /article -->
              <hr class="noscreen" />
          </div> <!-- /content -->



        </div> <!-- /page-in -->

      </div> <!-- /page -->

      <!-- Footer -->
      <div id="footer">
        <div id="top" class="noprint"><p><span class="noscreen">Back on top</span> <a href="#header" title="Back on top ^">^<span></span></a></p></div>
        <hr class="noscreen" />

      </div> <!-- /footer -->

    </div> <!-- /main -->


  </body>
</html>


</div>


</body></html>